spring.application.name=proyectoAplider

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dbaplider.postgres.database.azure.com/dbaplider
#spring.datasource.url=jdbc:postgresql://localhost/proyectoAplider
spring.datasource.username=useraplider
#spring.datasource.username=postgres
#spring.datasource.password=123
spring.datasource.password=aplider@434Kds

server.port=8082

