spring.application.name=proyectoAplider

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dbaplider.postgres.database.azure.com/dbaplider
spring.datasource.username=useraplider
spring.datasource.password=aplider@434Kds

server.port=8082